[project]
name = "codenames"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifultable>=1.1.0",
    "litellm>=1.79.1",
    "pydantic>=2.12.4",
]
